spring:
  profiles: dev
  redis:
    host: 172.16.105.145
    password: ""
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/grpc-test?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: root
  kafka:
    bootstrap-servers: 172.16.105.145:9092
eureka:
  client:
    service-url:
      defaultZone: http://discoveryservice.production.saas.dyrs.online/eureka/
logging:
  path: /data/logs
  pattern:
    level: INFO
