spring:
  profiles: dev
  redis:
    host: 172.16.105.145
    password: ""
    port: 6379
  datasource:
    url: jdbc:mysql://172.31.206.80:3306/grpc-test?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  kafka:
    bootstrap-servers: 172.16.105.145:9092
eureka:
  client:
    service-url:
      defaultZone: http://discoveryservice.production.saas.dyrs.online/eureka/
logging:
  path: D:\logs
  pattern:
    level: INFO
